import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Baseline migration capturing the production schema as of 2026-05-11.
 *
 * Generated by piping `pg_dump --schema-only --no-owner --no-privileges`
 * from the running production database into a Payload v3 migration file.
 * Hand-written because Payload's `migrate:create` CLI doesn't run against
 * this Node 20 / ESM-TS setup (same loader issue documented in the
 * project's schema_bootstrap memory).
 *
 * On prod this migration is pre-marked as applied in `payload_migrations`,
 * so the next `payload migrate` run will skip it without trying to
 * recreate existing tables. Its value is twofold:
 *
 *  1. Disaster recovery from an empty database — `payload migrate` against
 *     a fresh Postgres reproduces the entire schema.
 *  2. A known starting point for future Drizzle-driven migrations once
 *     the CLI environment is fixed.
 *
 * Known limitation: no companion `.json` Drizzle snapshot is produced
 * because we hand-wrote this. Until a snapshot is generated, future
 * `migrate:create` invocations may diff against an empty starting state
 * and emit spurious CREATE TABLE statements. Hand-write follow-up
 * migrations until the CLI bootstrap is solved.
 */

const UP_SQL = `
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;
COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';
CREATE TYPE public.enum__articles_v_version_original_source_wire_service AS ENUM (
    'none',
    'afp',
    'ap',
    'reuters',
    'anadolu',
    'aljazeera',
    'maan',
    'other'
);
CREATE TYPE public.enum__articles_v_version_status AS ENUM (
    'draft',
    'in-review',
    'published',
    'archived'
);
CREATE TYPE public.enum_ads_advertiser_type AS ENUM (
    'shop',
    'restaurant',
    'service',
    'event',
    'political',
    'nonprofit',
    'other'
);
CREATE TYPE public.enum_ads_placement AS ENUM (
    'header-banner',
    'sidebar-top',
    'sidebar-bottom',
    'between-articles',
    'article-inline',
    'article-end',
    'footer'
);
CREATE TYPE public.enum_ads_status AS ENUM (
    'draft',
    'active',
    'paused',
    'expired'
);
CREATE TYPE public.enum_article_reviews_status AS ENUM (
    'open',
    'resolved'
);
CREATE TYPE public.enum_articles_original_source_wire_service AS ENUM (
    'none',
    'afp',
    'ap',
    'reuters',
    'anadolu',
    'aljazeera',
    'maan',
    'other'
);
CREATE TYPE public.enum_articles_status AS ENUM (
    'draft',
    'in-review',
    'published',
    'archived'
);
CREATE TYPE public.enum_audit_log_action AS ENUM (
    'create',
    'update',
    'delete'
);
CREATE TYPE public.enum_locations_type AS ENUM (
    'neighborhood',
    'city',
    'region',
    'country',
    'other'
);
CREATE TYPE public.enum_media_license AS ENUM (
    'allRightsReserved',
    'cc-by',
    'cc-by-sa',
    'publicDomain',
    'licensed',
    'fairUse'
);
CREATE TYPE public.enum_notifications_type AS ENUM (
    'article.published',
    'article.in-review',
    'article.rejected',
    'article.publish-soon',
    'review.created',
    'system'
);
CREATE TYPE public.enum_series_status AS ENUM (
    'active',
    'archived'
);
CREATE TYPE public.enum_site_settings_announcement_variant AS ENUM (
    'info',
    'warning',
    'danger',
    'promo'
);
CREATE TYPE public.enum_site_settings_homepage_hero_mode AS ENUM (
    'auto',
    'manual'
);
CREATE TYPE public.enum_subscribers_preferences_frequency AS ENUM (
    'daily',
    'weekly',
    'breaking'
);
CREATE TYPE public.enum_users_role AS ENUM (
    'admin',
    'editor',
    'author'
);
CREATE TABLE public._articles_v (
    id integer NOT NULL,
    parent_id integer,
    version_status public.enum__articles_v_version_status DEFAULT 'draft'::public.enum__articles_v_version_status NOT NULL,
    version_published_at timestamp(3) with time zone,
    version_slug character varying NOT NULL,
    version_author_id integer,
    version_is_featured boolean DEFAULT false,
    version_is_breaking boolean DEFAULT false,
    version_views numeric DEFAULT 0,
    version_reading_time numeric DEFAULT 0,
    version_deleted_at timestamp(3) with time zone,
    version_title character varying NOT NULL,
    version_excerpt character varying NOT NULL,
    version_body jsonb NOT NULL,
    version_featured_image_id integer,
    version_category_id integer NOT NULL,
    version_series_id integer,
    version_seo_title character varying,
    version_seo_description character varying,
    version_seo_keywords character varying,
    version_og_image_id integer,
    version_canonical_url character varying,
    version_noindex boolean DEFAULT false,
    version_original_source_wire_service public.enum__articles_v_version_original_source_wire_service DEFAULT 'none'::public.enum__articles_v_version_original_source_wire_service,
    version_original_source_source_name character varying,
    version_original_source_source_url character varying,
    version_original_source_source_author character varying,
    version_internal_notes character varying,
    version_updated_at timestamp(3) with time zone,
    version_created_at timestamp(3) with time zone,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    version_video_url text
);
CREATE SEQUENCE public._articles_v_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public._articles_v_id_seq OWNED BY public._articles_v.id;
CREATE TABLE public._articles_v_rels (
    id integer NOT NULL,
    "order" integer,
    parent_id integer NOT NULL,
    path character varying NOT NULL,
    locations_id integer
);
CREATE SEQUENCE public._articles_v_rels_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public._articles_v_rels_id_seq OWNED BY public._articles_v_rels.id;
CREATE TABLE public._articles_v_version_gallery (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id integer NOT NULL,
    image_id integer NOT NULL,
    caption character varying,
    credit character varying,
    _uuid character varying
);
CREATE SEQUENCE public._articles_v_version_gallery_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public._articles_v_version_gallery_id_seq OWNED BY public._articles_v_version_gallery.id;
CREATE TABLE public._articles_v_version_tags (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id integer NOT NULL,
    tag character varying NOT NULL,
    _uuid character varying
);
CREATE SEQUENCE public._articles_v_version_tags_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public._articles_v_version_tags_id_seq OWNED BY public._articles_v_version_tags.id;
CREATE TABLE public.ads (
    id integer NOT NULL,
    status public.enum_ads_status DEFAULT 'draft'::public.enum_ads_status NOT NULL,
    placement public.enum_ads_placement NOT NULL,
    start_date timestamp(3) with time zone NOT NULL,
    end_date timestamp(3) with time zone NOT NULL,
    priority numeric DEFAULT 100,
    name character varying NOT NULL,
    image_id integer NOT NULL,
    image_mobile_id integer,
    headline character varying,
    body_text character varying,
    cta_text character varying DEFAULT 'اعرف أكثر'::character varying,
    target_url character varying NOT NULL,
    sponsored_label boolean DEFAULT true,
    advertiser character varying NOT NULL,
    advertiser_type public.enum_ads_advertiser_type DEFAULT 'shop'::public.enum_ads_advertiser_type,
    contact_person character varying,
    contact_email character varying,
    contact_phone character varying,
    price numeric,
    paid boolean DEFAULT false,
    invoice_number character varying,
    notes character varying,
    impressions numeric DEFAULT 0,
    clicks numeric DEFAULT 0,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);
CREATE SEQUENCE public.ads_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.ads_id_seq OWNED BY public.ads.id;
CREATE TABLE public.ads_rels (
    id integer NOT NULL,
    "order" integer,
    parent_id integer NOT NULL,
    path character varying NOT NULL,
    categories_id integer
);
CREATE SEQUENCE public.ads_rels_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.ads_rels_id_seq OWNED BY public.ads_rels.id;
CREATE TABLE public.article_embeddings (
    article_id integer NOT NULL,
    embedding public.vector(1536) NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.article_reviews (
    id integer NOT NULL,
    article_id integer NOT NULL,
    reviewer_id integer NOT NULL,
    summary character varying NOT NULL,
    content character varying NOT NULL,
    status public.enum_article_reviews_status DEFAULT 'open'::public.enum_article_reviews_status NOT NULL,
    resolved_at timestamp(3) with time zone,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);
CREATE SEQUENCE public.article_reviews_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.article_reviews_id_seq OWNED BY public.article_reviews.id;
CREATE TABLE public.articles (
    id integer NOT NULL,
    status public.enum_articles_status DEFAULT 'draft'::public.enum_articles_status NOT NULL,
    published_at timestamp(3) with time zone,
    slug character varying NOT NULL,
    author_id integer,
    is_featured boolean DEFAULT false,
    is_breaking boolean DEFAULT false,
    views numeric DEFAULT 0,
    reading_time numeric DEFAULT 0,
    deleted_at timestamp(3) with time zone,
    title character varying NOT NULL,
    excerpt character varying NOT NULL,
    body jsonb NOT NULL,
    featured_image_id integer,
    category_id integer NOT NULL,
    series_id integer,
    seo_title character varying,
    seo_description character varying,
    seo_keywords character varying,
    og_image_id integer,
    canonical_url character varying,
    noindex boolean DEFAULT false,
    original_source_wire_service public.enum_articles_original_source_wire_service DEFAULT 'none'::public.enum_articles_original_source_wire_service,
    original_source_source_name character varying,
    original_source_source_url character varying,
    original_source_source_author character varying,
    internal_notes character varying,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    video_url text
);
CREATE TABLE public.articles_gallery (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id character varying NOT NULL,
    image_id integer NOT NULL,
    caption character varying,
    credit character varying
);
CREATE SEQUENCE public.articles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.articles_id_seq OWNED BY public.articles.id;
CREATE TABLE public.articles_rels (
    id integer NOT NULL,
    "order" integer,
    parent_id integer NOT NULL,
    path character varying NOT NULL,
    locations_id integer
);
CREATE SEQUENCE public.articles_rels_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.articles_rels_id_seq OWNED BY public.articles_rels.id;
CREATE TABLE public.articles_tags (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id character varying NOT NULL,
    tag character varying NOT NULL
);
CREATE TABLE public.audit_log (
    id integer NOT NULL,
    action public.enum_audit_log_action NOT NULL,
    target_collection character varying NOT NULL,
    target_id character varying NOT NULL,
    user_id integer,
    user_name character varying,
    summary character varying,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);
CREATE SEQUENCE public.audit_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.audit_log_id_seq OWNED BY public.audit_log.id;
CREATE TABLE public.categories (
    id integer NOT NULL,
    name character varying NOT NULL,
    slug character varying NOT NULL,
    description character varying,
    color character varying,
    parent_id integer,
    "order" numeric DEFAULT 100,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);
CREATE SEQUENCE public.categories_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.categories_id_seq OWNED BY public.categories.id;
CREATE TABLE public.locations (
    id integer NOT NULL,
    name character varying NOT NULL,
    name_en character varying,
    type public.enum_locations_type DEFAULT 'city'::public.enum_locations_type NOT NULL,
    slug character varying NOT NULL,
    coordinates_lat numeric,
    coordinates_lng numeric,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);
CREATE SEQUENCE public.locations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.locations_id_seq OWNED BY public.locations.id;
CREATE TABLE public.media (
    id integer NOT NULL,
    alt character varying NOT NULL,
    caption character varying,
    photographer character varying,
    credit character varying,
    license public.enum_media_license DEFAULT 'allRightsReserved'::public.enum_media_license,
    source_url character varying,
    focal_point_x numeric DEFAULT 50,
    focal_point_y numeric DEFAULT 50,
    deleted_at timestamp(3) with time zone,
    prefix character varying DEFAULT 'media'::character varying,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    url character varying,
    thumbnail_u_r_l character varying,
    filename character varying,
    mime_type character varying,
    filesize numeric,
    width numeric,
    height numeric,
    focal_x numeric,
    focal_y numeric,
    sizes_thumbnail_url character varying,
    sizes_thumbnail_width numeric,
    sizes_thumbnail_height numeric,
    sizes_thumbnail_mime_type character varying,
    sizes_thumbnail_filesize numeric,
    sizes_thumbnail_filename character varying,
    sizes_card_url character varying,
    sizes_card_width numeric,
    sizes_card_height numeric,
    sizes_card_mime_type character varying,
    sizes_card_filesize numeric,
    sizes_card_filename character varying,
    sizes_hero_url character varying,
    sizes_hero_width numeric,
    sizes_hero_height numeric,
    sizes_hero_mime_type character varying,
    sizes_hero_filesize numeric,
    sizes_hero_filename character varying,
    sizes_full_url character varying,
    sizes_full_width numeric,
    sizes_full_height numeric,
    sizes_full_mime_type character varying,
    sizes_full_filesize numeric,
    sizes_full_filename character varying
);
CREATE SEQUENCE public.media_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.media_id_seq OWNED BY public.media.id;
CREATE TABLE public.notifications (
    id integer NOT NULL,
    recipient_id integer NOT NULL,
    type public.enum_notifications_type DEFAULT 'system'::public.enum_notifications_type NOT NULL,
    title character varying NOT NULL,
    message character varying,
    link character varying,
    related_article_id integer,
    read_at timestamp(3) with time zone,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);
CREATE SEQUENCE public.notifications_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.notifications_id_seq OWNED BY public.notifications.id;
CREATE TABLE public.page_views (
    id integer NOT NULL,
    article_id integer NOT NULL,
    date timestamp(3) with time zone NOT NULL,
    category_id integer,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);
CREATE SEQUENCE public.page_views_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.page_views_id_seq OWNED BY public.page_views.id;
CREATE TABLE public.pages (
    id integer NOT NULL,
    title character varying NOT NULL,
    slug character varying NOT NULL,
    body jsonb,
    published_at timestamp(3) with time zone,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);
CREATE SEQUENCE public.pages_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.pages_id_seq OWNED BY public.pages.id;
CREATE TABLE public.payload_kv (
    id integer NOT NULL,
    key character varying NOT NULL,
    data jsonb NOT NULL
);
CREATE SEQUENCE public.payload_kv_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.payload_kv_id_seq OWNED BY public.payload_kv.id;
CREATE TABLE public.payload_locked_documents (
    id integer NOT NULL,
    global_slug character varying,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);
CREATE SEQUENCE public.payload_locked_documents_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.payload_locked_documents_id_seq OWNED BY public.payload_locked_documents.id;
CREATE TABLE public.payload_locked_documents_rels (
    id integer NOT NULL,
    "order" integer,
    parent_id integer NOT NULL,
    path character varying NOT NULL,
    users_id integer,
    articles_id integer,
    categories_id integer,
    media_id integer,
    pages_id integer,
    series_id integer,
    locations_id integer,
    subscribers_id integer,
    page_views_id integer,
    audit_log_id integer,
    notifications_id integer,
    article_reviews_id integer,
    ads_id integer
);
CREATE SEQUENCE public.payload_locked_documents_rels_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.payload_locked_documents_rels_id_seq OWNED BY public.payload_locked_documents_rels.id;
CREATE TABLE public.payload_migrations (
    id integer NOT NULL,
    name character varying,
    batch numeric,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);
CREATE SEQUENCE public.payload_migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.payload_migrations_id_seq OWNED BY public.payload_migrations.id;
CREATE TABLE public.payload_preferences (
    id integer NOT NULL,
    key character varying,
    value jsonb,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);
CREATE SEQUENCE public.payload_preferences_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.payload_preferences_id_seq OWNED BY public.payload_preferences.id;
CREATE TABLE public.payload_preferences_rels (
    id integer NOT NULL,
    "order" integer,
    parent_id integer NOT NULL,
    path character varying NOT NULL,
    users_id integer
);
CREATE SEQUENCE public.payload_preferences_rels_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.payload_preferences_rels_id_seq OWNED BY public.payload_preferences_rels.id;
CREATE TABLE public.series (
    id integer NOT NULL,
    name character varying NOT NULL,
    slug character varying NOT NULL,
    status public.enum_series_status DEFAULT 'active'::public.enum_series_status NOT NULL,
    description character varying,
    cover_image_id integer,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);
CREATE SEQUENCE public.series_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.series_id_seq OWNED BY public.series.id;
CREATE TABLE public.site_settings (
    id integer NOT NULL,
    site_name character varying DEFAULT 'إرم 366 الإخبارية'::character varying,
    site_description character varying,
    logo_id integer,
    social_links_whatsapp character varying,
    social_links_instagram character varying,
    social_links_tiktok character varying,
    social_links_facebook character varying,
    social_links_email character varying,
    announcement_show boolean DEFAULT false,
    announcement_message character varying,
    announcement_variant public.enum_site_settings_announcement_variant DEFAULT 'info'::public.enum_site_settings_announcement_variant,
    announcement_link character varying,
    announcement_dismissible boolean DEFAULT true,
    homepage_hero_mode public.enum_site_settings_homepage_hero_mode DEFAULT 'auto'::public.enum_site_settings_homepage_hero_mode NOT NULL,
    homepage_hero_main_article_id integer,
    footer_text character varying,
    updated_at timestamp(3) with time zone,
    created_at timestamp(3) with time zone,
    social_links_youtube text,
    social_links_telegram text
);
CREATE SEQUENCE public.site_settings_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.site_settings_id_seq OWNED BY public.site_settings.id;
CREATE TABLE public.site_settings_rels (
    id integer NOT NULL,
    "order" integer,
    parent_id integer NOT NULL,
    path character varying NOT NULL,
    articles_id integer
);
CREATE SEQUENCE public.site_settings_rels_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.site_settings_rels_id_seq OWNED BY public.site_settings_rels.id;
CREATE TABLE public.subscribers (
    id integer NOT NULL,
    email character varying NOT NULL,
    verified_at timestamp(3) with time zone,
    unsubscribed_at timestamp(3) with time zone,
    source character varying DEFAULT 'website'::character varying,
    preferences_frequency public.enum_subscribers_preferences_frequency DEFAULT 'weekly'::public.enum_subscribers_preferences_frequency,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);
CREATE SEQUENCE public.subscribers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.subscribers_id_seq OWNED BY public.subscribers.id;
CREATE TABLE public.users (
    id integer NOT NULL,
    name character varying NOT NULL,
    role public.enum_users_role DEFAULT 'editor'::public.enum_users_role NOT NULL,
    avatar_id integer,
    "position" character varying,
    bio character varying,
    twitter character varying,
    joined_at timestamp(3) with time zone,
    deleted_at timestamp(3) with time zone,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    email character varying NOT NULL,
    reset_password_token character varying,
    reset_password_expiration timestamp(3) with time zone,
    salt character varying,
    hash character varying,
    login_attempts numeric DEFAULT 0,
    lock_until timestamp(3) with time zone
);
CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;
CREATE TABLE public.users_sessions (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id character varying NOT NULL,
    created_at timestamp(3) with time zone,
    expires_at timestamp(3) with time zone NOT NULL
);
ALTER TABLE ONLY public._articles_v ALTER COLUMN id SET DEFAULT nextval('public._articles_v_id_seq'::regclass);
ALTER TABLE ONLY public._articles_v_rels ALTER COLUMN id SET DEFAULT nextval('public._articles_v_rels_id_seq'::regclass);
ALTER TABLE ONLY public._articles_v_version_gallery ALTER COLUMN id SET DEFAULT nextval('public._articles_v_version_gallery_id_seq'::regclass);
ALTER TABLE ONLY public._articles_v_version_tags ALTER COLUMN id SET DEFAULT nextval('public._articles_v_version_tags_id_seq'::regclass);
ALTER TABLE ONLY public.ads ALTER COLUMN id SET DEFAULT nextval('public.ads_id_seq'::regclass);
ALTER TABLE ONLY public.ads_rels ALTER COLUMN id SET DEFAULT nextval('public.ads_rels_id_seq'::regclass);
ALTER TABLE ONLY public.article_reviews ALTER COLUMN id SET DEFAULT nextval('public.article_reviews_id_seq'::regclass);
ALTER TABLE ONLY public.articles ALTER COLUMN id SET DEFAULT nextval('public.articles_id_seq'::regclass);
ALTER TABLE ONLY public.articles_rels ALTER COLUMN id SET DEFAULT nextval('public.articles_rels_id_seq'::regclass);
ALTER TABLE ONLY public.audit_log ALTER COLUMN id SET DEFAULT nextval('public.audit_log_id_seq'::regclass);
ALTER TABLE ONLY public.categories ALTER COLUMN id SET DEFAULT nextval('public.categories_id_seq'::regclass);
ALTER TABLE ONLY public.locations ALTER COLUMN id SET DEFAULT nextval('public.locations_id_seq'::regclass);
ALTER TABLE ONLY public.media ALTER COLUMN id SET DEFAULT nextval('public.media_id_seq'::regclass);
ALTER TABLE ONLY public.notifications ALTER COLUMN id SET DEFAULT nextval('public.notifications_id_seq'::regclass);
ALTER TABLE ONLY public.page_views ALTER COLUMN id SET DEFAULT nextval('public.page_views_id_seq'::regclass);
ALTER TABLE ONLY public.pages ALTER COLUMN id SET DEFAULT nextval('public.pages_id_seq'::regclass);
ALTER TABLE ONLY public.payload_kv ALTER COLUMN id SET DEFAULT nextval('public.payload_kv_id_seq'::regclass);
ALTER TABLE ONLY public.payload_locked_documents ALTER COLUMN id SET DEFAULT nextval('public.payload_locked_documents_id_seq'::regclass);
ALTER TABLE ONLY public.payload_locked_documents_rels ALTER COLUMN id SET DEFAULT nextval('public.payload_locked_documents_rels_id_seq'::regclass);
ALTER TABLE ONLY public.payload_migrations ALTER COLUMN id SET DEFAULT nextval('public.payload_migrations_id_seq'::regclass);
ALTER TABLE ONLY public.payload_preferences ALTER COLUMN id SET DEFAULT nextval('public.payload_preferences_id_seq'::regclass);
ALTER TABLE ONLY public.payload_preferences_rels ALTER COLUMN id SET DEFAULT nextval('public.payload_preferences_rels_id_seq'::regclass);
ALTER TABLE ONLY public.series ALTER COLUMN id SET DEFAULT nextval('public.series_id_seq'::regclass);
ALTER TABLE ONLY public.site_settings ALTER COLUMN id SET DEFAULT nextval('public.site_settings_id_seq'::regclass);
ALTER TABLE ONLY public.site_settings_rels ALTER COLUMN id SET DEFAULT nextval('public.site_settings_rels_id_seq'::regclass);
ALTER TABLE ONLY public.subscribers ALTER COLUMN id SET DEFAULT nextval('public.subscribers_id_seq'::regclass);
ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);
ALTER TABLE ONLY public._articles_v
    ADD CONSTRAINT _articles_v_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public._articles_v_rels
    ADD CONSTRAINT _articles_v_rels_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public._articles_v_version_gallery
    ADD CONSTRAINT _articles_v_version_gallery_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public._articles_v_version_tags
    ADD CONSTRAINT _articles_v_version_tags_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ads
    ADD CONSTRAINT ads_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ads_rels
    ADD CONSTRAINT ads_rels_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.article_embeddings
    ADD CONSTRAINT article_embeddings_pkey PRIMARY KEY (article_id);
ALTER TABLE ONLY public.article_reviews
    ADD CONSTRAINT article_reviews_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.articles_gallery
    ADD CONSTRAINT articles_gallery_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.articles_rels
    ADD CONSTRAINT articles_rels_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.articles_tags
    ADD CONSTRAINT articles_tags_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.page_views
    ADD CONSTRAINT page_views_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.pages
    ADD CONSTRAINT pages_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payload_kv
    ADD CONSTRAINT payload_kv_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payload_locked_documents
    ADD CONSTRAINT payload_locked_documents_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payload_locked_documents_rels
    ADD CONSTRAINT payload_locked_documents_rels_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payload_migrations
    ADD CONSTRAINT payload_migrations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payload_preferences
    ADD CONSTRAINT payload_preferences_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payload_preferences_rels
    ADD CONSTRAINT payload_preferences_rels_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.site_settings
    ADD CONSTRAINT site_settings_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.site_settings_rels
    ADD CONSTRAINT site_settings_rels_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.subscribers
    ADD CONSTRAINT subscribers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users_sessions
    ADD CONSTRAINT users_sessions_pkey PRIMARY KEY (id);
CREATE INDEX _articles_v_created_at_idx ON public._articles_v USING btree (created_at);
CREATE INDEX _articles_v_parent_idx ON public._articles_v USING btree (parent_id);
CREATE INDEX _articles_v_rels_locations_id_idx ON public._articles_v_rels USING btree (locations_id);
CREATE INDEX _articles_v_rels_order_idx ON public._articles_v_rels USING btree ("order");
CREATE INDEX _articles_v_rels_parent_idx ON public._articles_v_rels USING btree (parent_id);
CREATE INDEX _articles_v_rels_path_idx ON public._articles_v_rels USING btree (path);
CREATE INDEX _articles_v_updated_at_idx ON public._articles_v USING btree (updated_at);
CREATE INDEX _articles_v_version_gallery_image_idx ON public._articles_v_version_gallery USING btree (image_id);
CREATE INDEX _articles_v_version_gallery_order_idx ON public._articles_v_version_gallery USING btree (_order);
CREATE INDEX _articles_v_version_gallery_parent_id_idx ON public._articles_v_version_gallery USING btree (_parent_id);
CREATE INDEX _articles_v_version_tags_order_idx ON public._articles_v_version_tags USING btree (_order);
CREATE INDEX _articles_v_version_tags_parent_id_idx ON public._articles_v_version_tags USING btree (_parent_id);
CREATE INDEX _articles_v_version_version_author_idx ON public._articles_v USING btree (version_author_id);
CREATE INDEX _articles_v_version_version_category_idx ON public._articles_v USING btree (version_category_id);
CREATE INDEX _articles_v_version_version_created_at_idx ON public._articles_v USING btree (version_created_at);
CREATE INDEX _articles_v_version_version_deleted_at_idx ON public._articles_v USING btree (version_deleted_at);
CREATE INDEX _articles_v_version_version_featured_image_idx ON public._articles_v USING btree (version_featured_image_id);
CREATE INDEX _articles_v_version_version_is_breaking_idx ON public._articles_v USING btree (version_is_breaking);
CREATE INDEX _articles_v_version_version_is_featured_idx ON public._articles_v USING btree (version_is_featured);
CREATE INDEX _articles_v_version_version_og_image_idx ON public._articles_v USING btree (version_og_image_id);
CREATE INDEX _articles_v_version_version_published_at_idx ON public._articles_v USING btree (version_published_at);
CREATE INDEX _articles_v_version_version_series_idx ON public._articles_v USING btree (version_series_id);
CREATE INDEX _articles_v_version_version_slug_idx ON public._articles_v USING btree (version_slug);
CREATE INDEX _articles_v_version_version_status_idx ON public._articles_v USING btree (version_status);
CREATE INDEX _articles_v_version_version_updated_at_idx ON public._articles_v USING btree (version_updated_at);
CREATE INDEX ads_created_at_idx ON public.ads USING btree (created_at);
CREATE INDEX ads_end_date_idx ON public.ads USING btree (end_date);
CREATE INDEX ads_image_idx ON public.ads USING btree (image_id);
CREATE INDEX ads_image_mobile_idx ON public.ads USING btree (image_mobile_id);
CREATE INDEX ads_placement_idx ON public.ads USING btree (placement);
CREATE INDEX ads_rels_categories_id_idx ON public.ads_rels USING btree (categories_id);
CREATE INDEX ads_rels_order_idx ON public.ads_rels USING btree ("order");
CREATE INDEX ads_rels_parent_idx ON public.ads_rels USING btree (parent_id);
CREATE INDEX ads_rels_path_idx ON public.ads_rels USING btree (path);
CREATE INDEX ads_start_date_idx ON public.ads USING btree (start_date);
CREATE INDEX ads_status_idx ON public.ads USING btree (status);
CREATE INDEX ads_updated_at_idx ON public.ads USING btree (updated_at);
CREATE INDEX article_embeddings_cosine_idx ON public.article_embeddings USING ivfflat (embedding public.vector_cosine_ops) WITH (lists='50');
CREATE INDEX article_reviews_article_idx ON public.article_reviews USING btree (article_id);
CREATE INDEX article_reviews_created_at_idx ON public.article_reviews USING btree (created_at);
CREATE INDEX article_reviews_reviewer_idx ON public.article_reviews USING btree (reviewer_id);
CREATE INDEX article_reviews_status_idx ON public.article_reviews USING btree (status);
CREATE INDEX article_reviews_updated_at_idx ON public.article_reviews USING btree (updated_at);
CREATE INDEX articles_author_idx ON public.articles USING btree (author_id);
CREATE INDEX articles_category_idx ON public.articles USING btree (category_id);
CREATE INDEX articles_created_at_idx ON public.articles USING btree (created_at);
CREATE INDEX articles_deleted_at_idx ON public.articles USING btree (deleted_at);
CREATE INDEX articles_featured_image_idx ON public.articles USING btree (featured_image_id);
CREATE INDEX articles_gallery_image_idx ON public.articles_gallery USING btree (image_id);
CREATE INDEX articles_gallery_order_idx ON public.articles_gallery USING btree (_order);
CREATE INDEX articles_gallery_parent_id_idx ON public.articles_gallery USING btree (_parent_id);
CREATE INDEX articles_is_breaking_idx ON public.articles USING btree (is_breaking);
CREATE INDEX articles_is_featured_idx ON public.articles USING btree (is_featured);
CREATE INDEX articles_og_image_idx ON public.articles USING btree (og_image_id);
CREATE INDEX articles_published_at_idx ON public.articles USING btree (published_at);
CREATE INDEX articles_rels_locations_id_idx ON public.articles_rels USING btree (locations_id);
CREATE INDEX articles_rels_order_idx ON public.articles_rels USING btree ("order");
CREATE INDEX articles_rels_parent_idx ON public.articles_rels USING btree (parent_id);
CREATE INDEX articles_rels_path_idx ON public.articles_rels USING btree (path);
CREATE INDEX articles_series_idx ON public.articles USING btree (series_id);
CREATE UNIQUE INDEX articles_slug_idx ON public.articles USING btree (slug);
CREATE INDEX articles_status_idx ON public.articles USING btree (status);
CREATE INDEX articles_tags_order_idx ON public.articles_tags USING btree (_order);
CREATE INDEX articles_tags_parent_id_idx ON public.articles_tags USING btree (_parent_id);
CREATE INDEX articles_updated_at_idx ON public.articles USING btree (updated_at);
CREATE INDEX audit_log_created_at_idx ON public.audit_log USING btree (created_at);
CREATE INDEX audit_log_target_collection_idx ON public.audit_log USING btree (target_collection);
CREATE INDEX audit_log_target_id_idx ON public.audit_log USING btree (target_id);
CREATE INDEX audit_log_updated_at_idx ON public.audit_log USING btree (updated_at);
CREATE INDEX audit_log_user_idx ON public.audit_log USING btree (user_id);
CREATE INDEX categories_created_at_idx ON public.categories USING btree (created_at);
CREATE UNIQUE INDEX categories_name_idx ON public.categories USING btree (name);
CREATE INDEX categories_order_idx ON public.categories USING btree ("order");
CREATE INDEX categories_parent_idx ON public.categories USING btree (parent_id);
CREATE UNIQUE INDEX categories_slug_idx ON public.categories USING btree (slug);
CREATE INDEX categories_updated_at_idx ON public.categories USING btree (updated_at);
CREATE INDEX locations_created_at_idx ON public.locations USING btree (created_at);
CREATE UNIQUE INDEX locations_slug_idx ON public.locations USING btree (slug);
CREATE INDEX locations_updated_at_idx ON public.locations USING btree (updated_at);
CREATE INDEX media_created_at_idx ON public.media USING btree (created_at);
CREATE INDEX media_deleted_at_idx ON public.media USING btree (deleted_at);
CREATE UNIQUE INDEX media_filename_idx ON public.media USING btree (filename);
CREATE INDEX media_sizes_card_sizes_card_filename_idx ON public.media USING btree (sizes_card_filename);
CREATE INDEX media_sizes_full_sizes_full_filename_idx ON public.media USING btree (sizes_full_filename);
CREATE INDEX media_sizes_hero_sizes_hero_filename_idx ON public.media USING btree (sizes_hero_filename);
CREATE INDEX media_sizes_thumbnail_sizes_thumbnail_filename_idx ON public.media USING btree (sizes_thumbnail_filename);
CREATE INDEX media_updated_at_idx ON public.media USING btree (updated_at);
CREATE INDEX notifications_created_at_idx ON public.notifications USING btree (created_at);
CREATE INDEX notifications_read_at_idx ON public.notifications USING btree (read_at);
CREATE INDEX notifications_recipient_idx ON public.notifications USING btree (recipient_id);
CREATE INDEX notifications_related_article_idx ON public.notifications USING btree (related_article_id);
CREATE INDEX notifications_type_idx ON public.notifications USING btree (type);
CREATE INDEX notifications_updated_at_idx ON public.notifications USING btree (updated_at);
CREATE INDEX page_views_article_idx ON public.page_views USING btree (article_id);
CREATE INDEX page_views_category_idx ON public.page_views USING btree (category_id);
CREATE INDEX page_views_created_at_idx ON public.page_views USING btree (created_at);
CREATE INDEX page_views_date_idx ON public.page_views USING btree (date);
CREATE INDEX page_views_updated_at_idx ON public.page_views USING btree (updated_at);
CREATE INDEX pages_created_at_idx ON public.pages USING btree (created_at);
CREATE UNIQUE INDEX pages_slug_idx ON public.pages USING btree (slug);
CREATE INDEX pages_updated_at_idx ON public.pages USING btree (updated_at);
CREATE UNIQUE INDEX payload_kv_key_idx ON public.payload_kv USING btree (key);
CREATE INDEX payload_locked_documents_created_at_idx ON public.payload_locked_documents USING btree (created_at);
CREATE INDEX payload_locked_documents_global_slug_idx ON public.payload_locked_documents USING btree (global_slug);
CREATE INDEX payload_locked_documents_rels_ads_id_idx ON public.payload_locked_documents_rels USING btree (ads_id);
CREATE INDEX payload_locked_documents_rels_article_reviews_id_idx ON public.payload_locked_documents_rels USING btree (article_reviews_id);
CREATE INDEX payload_locked_documents_rels_articles_id_idx ON public.payload_locked_documents_rels USING btree (articles_id);
CREATE INDEX payload_locked_documents_rels_audit_log_id_idx ON public.payload_locked_documents_rels USING btree (audit_log_id);
CREATE INDEX payload_locked_documents_rels_categories_id_idx ON public.payload_locked_documents_rels USING btree (categories_id);
CREATE INDEX payload_locked_documents_rels_locations_id_idx ON public.payload_locked_documents_rels USING btree (locations_id);
CREATE INDEX payload_locked_documents_rels_media_id_idx ON public.payload_locked_documents_rels USING btree (media_id);
CREATE INDEX payload_locked_documents_rels_notifications_id_idx ON public.payload_locked_documents_rels USING btree (notifications_id);
CREATE INDEX payload_locked_documents_rels_order_idx ON public.payload_locked_documents_rels USING btree ("order");
CREATE INDEX payload_locked_documents_rels_page_views_id_idx ON public.payload_locked_documents_rels USING btree (page_views_id);
CREATE INDEX payload_locked_documents_rels_pages_id_idx ON public.payload_locked_documents_rels USING btree (pages_id);
CREATE INDEX payload_locked_documents_rels_parent_idx ON public.payload_locked_documents_rels USING btree (parent_id);
CREATE INDEX payload_locked_documents_rels_path_idx ON public.payload_locked_documents_rels USING btree (path);
CREATE INDEX payload_locked_documents_rels_series_id_idx ON public.payload_locked_documents_rels USING btree (series_id);
CREATE INDEX payload_locked_documents_rels_subscribers_id_idx ON public.payload_locked_documents_rels USING btree (subscribers_id);
CREATE INDEX payload_locked_documents_rels_users_id_idx ON public.payload_locked_documents_rels USING btree (users_id);
CREATE INDEX payload_locked_documents_updated_at_idx ON public.payload_locked_documents USING btree (updated_at);
CREATE INDEX payload_migrations_created_at_idx ON public.payload_migrations USING btree (created_at);
CREATE INDEX payload_migrations_updated_at_idx ON public.payload_migrations USING btree (updated_at);
CREATE INDEX payload_preferences_created_at_idx ON public.payload_preferences USING btree (created_at);
CREATE INDEX payload_preferences_key_idx ON public.payload_preferences USING btree (key);
CREATE INDEX payload_preferences_rels_order_idx ON public.payload_preferences_rels USING btree ("order");
CREATE INDEX payload_preferences_rels_parent_idx ON public.payload_preferences_rels USING btree (parent_id);
CREATE INDEX payload_preferences_rels_path_idx ON public.payload_preferences_rels USING btree (path);
CREATE INDEX payload_preferences_rels_users_id_idx ON public.payload_preferences_rels USING btree (users_id);
CREATE INDEX payload_preferences_updated_at_idx ON public.payload_preferences USING btree (updated_at);
CREATE INDEX series_cover_image_idx ON public.series USING btree (cover_image_id);
CREATE INDEX series_created_at_idx ON public.series USING btree (created_at);
CREATE UNIQUE INDEX series_slug_idx ON public.series USING btree (slug);
CREATE INDEX series_updated_at_idx ON public.series USING btree (updated_at);
CREATE INDEX site_settings_homepage_hero_homepage_hero_main_article_idx ON public.site_settings USING btree (homepage_hero_main_article_id);
CREATE INDEX site_settings_logo_idx ON public.site_settings USING btree (logo_id);
CREATE INDEX site_settings_rels_articles_id_idx ON public.site_settings_rels USING btree (articles_id);
CREATE INDEX site_settings_rels_order_idx ON public.site_settings_rels USING btree ("order");
CREATE INDEX site_settings_rels_parent_idx ON public.site_settings_rels USING btree (parent_id);
CREATE INDEX site_settings_rels_path_idx ON public.site_settings_rels USING btree (path);
CREATE INDEX subscribers_created_at_idx ON public.subscribers USING btree (created_at);
CREATE UNIQUE INDEX subscribers_email_idx ON public.subscribers USING btree (email);
CREATE INDEX subscribers_unsubscribed_at_idx ON public.subscribers USING btree (unsubscribed_at);
CREATE INDEX subscribers_updated_at_idx ON public.subscribers USING btree (updated_at);
CREATE INDEX users_avatar_idx ON public.users USING btree (avatar_id);
CREATE INDEX users_created_at_idx ON public.users USING btree (created_at);
CREATE INDEX users_deleted_at_idx ON public.users USING btree (deleted_at);
CREATE UNIQUE INDEX users_email_idx ON public.users USING btree (email);
CREATE INDEX users_joined_at_idx ON public.users USING btree (joined_at);
CREATE INDEX users_sessions_order_idx ON public.users_sessions USING btree (_order);
CREATE INDEX users_sessions_parent_id_idx ON public.users_sessions USING btree (_parent_id);
CREATE INDEX users_updated_at_idx ON public.users USING btree (updated_at);
ALTER TABLE ONLY public._articles_v
    ADD CONSTRAINT _articles_v_parent_id_articles_id_fk FOREIGN KEY (parent_id) REFERENCES public.articles(id) ON DELETE SET NULL;
ALTER TABLE ONLY public._articles_v_rels
    ADD CONSTRAINT _articles_v_rels_locations_fk FOREIGN KEY (locations_id) REFERENCES public.locations(id) ON DELETE CASCADE;
ALTER TABLE ONLY public._articles_v_rels
    ADD CONSTRAINT _articles_v_rels_parent_fk FOREIGN KEY (parent_id) REFERENCES public._articles_v(id) ON DELETE CASCADE;
ALTER TABLE ONLY public._articles_v
    ADD CONSTRAINT _articles_v_version_author_id_users_id_fk FOREIGN KEY (version_author_id) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE ONLY public._articles_v
    ADD CONSTRAINT _articles_v_version_category_id_categories_id_fk FOREIGN KEY (version_category_id) REFERENCES public.categories(id) ON DELETE SET NULL;
ALTER TABLE ONLY public._articles_v
    ADD CONSTRAINT _articles_v_version_featured_image_id_media_id_fk FOREIGN KEY (version_featured_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
ALTER TABLE ONLY public._articles_v_version_gallery
    ADD CONSTRAINT _articles_v_version_gallery_image_id_media_id_fk FOREIGN KEY (image_id) REFERENCES public.media(id) ON DELETE SET NULL;
ALTER TABLE ONLY public._articles_v_version_gallery
    ADD CONSTRAINT _articles_v_version_gallery_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public._articles_v(id) ON DELETE CASCADE;
ALTER TABLE ONLY public._articles_v
    ADD CONSTRAINT _articles_v_version_og_image_id_media_id_fk FOREIGN KEY (version_og_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
ALTER TABLE ONLY public._articles_v
    ADD CONSTRAINT _articles_v_version_series_id_series_id_fk FOREIGN KEY (version_series_id) REFERENCES public.series(id) ON DELETE SET NULL;
ALTER TABLE ONLY public._articles_v_version_tags
    ADD CONSTRAINT _articles_v_version_tags_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public._articles_v(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ads
    ADD CONSTRAINT ads_image_id_media_id_fk FOREIGN KEY (image_id) REFERENCES public.media(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.ads
    ADD CONSTRAINT ads_image_mobile_id_media_id_fk FOREIGN KEY (image_mobile_id) REFERENCES public.media(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.ads_rels
    ADD CONSTRAINT ads_rels_categories_fk FOREIGN KEY (categories_id) REFERENCES public.categories(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ads_rels
    ADD CONSTRAINT ads_rels_parent_fk FOREIGN KEY (parent_id) REFERENCES public.ads(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.article_embeddings
    ADD CONSTRAINT article_embeddings_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.articles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.article_reviews
    ADD CONSTRAINT article_reviews_article_id_articles_id_fk FOREIGN KEY (article_id) REFERENCES public.articles(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.article_reviews
    ADD CONSTRAINT article_reviews_reviewer_id_users_id_fk FOREIGN KEY (reviewer_id) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_author_id_users_id_fk FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_category_id_categories_id_fk FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_featured_image_id_media_id_fk FOREIGN KEY (featured_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.articles_gallery
    ADD CONSTRAINT articles_gallery_image_id_media_id_fk FOREIGN KEY (image_id) REFERENCES public.media(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.articles_gallery
    ADD CONSTRAINT articles_gallery_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.articles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_og_image_id_media_id_fk FOREIGN KEY (og_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.articles_rels
    ADD CONSTRAINT articles_rels_locations_fk FOREIGN KEY (locations_id) REFERENCES public.locations(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.articles_rels
    ADD CONSTRAINT articles_rels_parent_fk FOREIGN KEY (parent_id) REFERENCES public.articles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_series_id_series_id_fk FOREIGN KEY (series_id) REFERENCES public.series(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.articles_tags
    ADD CONSTRAINT articles_tags_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.articles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_parent_id_categories_id_fk FOREIGN KEY (parent_id) REFERENCES public.categories(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_recipient_id_users_id_fk FOREIGN KEY (recipient_id) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_related_article_id_articles_id_fk FOREIGN KEY (related_article_id) REFERENCES public.articles(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.page_views
    ADD CONSTRAINT page_views_article_id_articles_id_fk FOREIGN KEY (article_id) REFERENCES public.articles(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.page_views
    ADD CONSTRAINT page_views_category_id_categories_id_fk FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.payload_locked_documents_rels
    ADD CONSTRAINT payload_locked_documents_rels_ads_fk FOREIGN KEY (ads_id) REFERENCES public.ads(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payload_locked_documents_rels
    ADD CONSTRAINT payload_locked_documents_rels_article_reviews_fk FOREIGN KEY (article_reviews_id) REFERENCES public.article_reviews(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payload_locked_documents_rels
    ADD CONSTRAINT payload_locked_documents_rels_articles_fk FOREIGN KEY (articles_id) REFERENCES public.articles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payload_locked_documents_rels
    ADD CONSTRAINT payload_locked_documents_rels_audit_log_fk FOREIGN KEY (audit_log_id) REFERENCES public.audit_log(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payload_locked_documents_rels
    ADD CONSTRAINT payload_locked_documents_rels_categories_fk FOREIGN KEY (categories_id) REFERENCES public.categories(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payload_locked_documents_rels
    ADD CONSTRAINT payload_locked_documents_rels_locations_fk FOREIGN KEY (locations_id) REFERENCES public.locations(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payload_locked_documents_rels
    ADD CONSTRAINT payload_locked_documents_rels_media_fk FOREIGN KEY (media_id) REFERENCES public.media(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payload_locked_documents_rels
    ADD CONSTRAINT payload_locked_documents_rels_notifications_fk FOREIGN KEY (notifications_id) REFERENCES public.notifications(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payload_locked_documents_rels
    ADD CONSTRAINT payload_locked_documents_rels_page_views_fk FOREIGN KEY (page_views_id) REFERENCES public.page_views(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payload_locked_documents_rels
    ADD CONSTRAINT payload_locked_documents_rels_pages_fk FOREIGN KEY (pages_id) REFERENCES public.pages(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payload_locked_documents_rels
    ADD CONSTRAINT payload_locked_documents_rels_parent_fk FOREIGN KEY (parent_id) REFERENCES public.payload_locked_documents(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payload_locked_documents_rels
    ADD CONSTRAINT payload_locked_documents_rels_series_fk FOREIGN KEY (series_id) REFERENCES public.series(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payload_locked_documents_rels
    ADD CONSTRAINT payload_locked_documents_rels_subscribers_fk FOREIGN KEY (subscribers_id) REFERENCES public.subscribers(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payload_locked_documents_rels
    ADD CONSTRAINT payload_locked_documents_rels_users_fk FOREIGN KEY (users_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payload_preferences_rels
    ADD CONSTRAINT payload_preferences_rels_parent_fk FOREIGN KEY (parent_id) REFERENCES public.payload_preferences(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payload_preferences_rels
    ADD CONSTRAINT payload_preferences_rels_users_fk FOREIGN KEY (users_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_cover_image_id_media_id_fk FOREIGN KEY (cover_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.site_settings
    ADD CONSTRAINT site_settings_homepage_hero_main_article_id_articles_id_fk FOREIGN KEY (homepage_hero_main_article_id) REFERENCES public.articles(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.site_settings
    ADD CONSTRAINT site_settings_logo_id_media_id_fk FOREIGN KEY (logo_id) REFERENCES public.media(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.site_settings_rels
    ADD CONSTRAINT site_settings_rels_articles_fk FOREIGN KEY (articles_id) REFERENCES public.articles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.site_settings_rels
    ADD CONSTRAINT site_settings_rels_parent_fk FOREIGN KEY (parent_id) REFERENCES public.site_settings(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_avatar_id_media_id_fk FOREIGN KEY (avatar_id) REFERENCES public.media(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.users_sessions
    ADD CONSTRAINT users_sessions_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES public.users(id) ON DELETE CASCADE;
`

const DOWN_SQL = `
-- Reverse of the baseline: drop everything the up() created.
-- CASCADE handles FK dependencies so ordering within each group is moot.

-- Tables
DROP TABLE IF EXISTS public.users_sessions CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.subscribers CASCADE;
DROP TABLE IF EXISTS public.site_settings_rels CASCADE;
DROP TABLE IF EXISTS public.site_settings CASCADE;
DROP TABLE IF EXISTS public.series CASCADE;
DROP TABLE IF EXISTS public.payload_preferences_rels CASCADE;
DROP TABLE IF EXISTS public.payload_preferences CASCADE;
DROP TABLE IF EXISTS public.payload_migrations CASCADE;
DROP TABLE IF EXISTS public.payload_locked_documents_rels CASCADE;
DROP TABLE IF EXISTS public.payload_locked_documents CASCADE;
DROP TABLE IF EXISTS public.payload_kv CASCADE;
DROP TABLE IF EXISTS public.page_views CASCADE;
DROP TABLE IF EXISTS public.pages CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.media CASCADE;
DROP TABLE IF EXISTS public.locations CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.audit_log CASCADE;
DROP TABLE IF EXISTS public._articles_v_version_tags CASCADE;
DROP TABLE IF EXISTS public._articles_v_version_gallery CASCADE;
DROP TABLE IF EXISTS public._articles_v_rels CASCADE;
DROP TABLE IF EXISTS public._articles_v CASCADE;
DROP TABLE IF EXISTS public.articles_tags CASCADE;
DROP TABLE IF EXISTS public.articles_rels CASCADE;
DROP TABLE IF EXISTS public.articles_gallery CASCADE;
DROP TABLE IF EXISTS public.articles CASCADE;
DROP TABLE IF EXISTS public.article_reviews CASCADE;
DROP TABLE IF EXISTS public.article_embeddings CASCADE;
DROP TABLE IF EXISTS public.ads_rels CASCADE;
DROP TABLE IF EXISTS public.ads CASCADE;

-- Enum types
DROP TYPE IF EXISTS public.enum__articles_v_version_original_source_wire_service CASCADE;
DROP TYPE IF EXISTS public.enum__articles_v_version_status CASCADE;
DROP TYPE IF EXISTS public.enum_ads_advertiser_type CASCADE;
DROP TYPE IF EXISTS public.enum_ads_placement CASCADE;
DROP TYPE IF EXISTS public.enum_ads_status CASCADE;
DROP TYPE IF EXISTS public.enum_article_reviews_status CASCADE;
DROP TYPE IF EXISTS public.enum_articles_original_source_wire_service CASCADE;
DROP TYPE IF EXISTS public.enum_articles_status CASCADE;
DROP TYPE IF EXISTS public.enum_audit_log_action CASCADE;
DROP TYPE IF EXISTS public.enum_locations_type CASCADE;
DROP TYPE IF EXISTS public.enum_media_license CASCADE;
DROP TYPE IF EXISTS public.enum_notifications_type CASCADE;
DROP TYPE IF EXISTS public.enum_series_status CASCADE;
DROP TYPE IF EXISTS public.enum_site_settings_announcement_variant CASCADE;
DROP TYPE IF EXISTS public.enum_site_settings_homepage_hero_mode CASCADE;
DROP TYPE IF EXISTS public.enum_subscribers_preferences_frequency CASCADE;
DROP TYPE IF EXISTS public.enum_users_role CASCADE;

-- Extension
DROP EXTENSION IF EXISTS vector CASCADE;
`

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql.raw(UP_SQL))
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql.raw(DOWN_SQL))
}
